import { memo, useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';

// Each showcase item pairs a video (optional) with a fallback poster image.
// Videos are in frontend/public/showcase/ — generated by scripts/generate_showcase.py.
// If a video 404s or fails to load, the poster image is shown instead.
const SHOWCASE_ITEMS = [
  { video: '/showcase/pixel-hero-1.mp4',  poster: '/showcase/pixel-hero-1.png' },
  { video: '/showcase/cyber-nova-1.mp4',  poster: '/showcase/cyber-nova-1.png' },
  { video: '/showcase/watercolor-1.mp4',  poster: '/showcase/watercolor-1.png' },
  { video: '/showcase/figurine-1.mp4',    poster: '/showcase/figurine-1.png' },
  { video: '/showcase/manga-1.mp4',       poster: '/showcase/manga-1.png' },
  { video: '/showcase/brick-1.mp4',       poster: '/showcase/brick-1.png' },
  { video: '/showcase/pixel-hero-2.mp4',  poster: '/showcase/pixel-hero-2.png' },
  { video: '/showcase/cyber-nova-2.mp4',  poster: '/showcase/cyber-nova-2.png' },
  { video: '/showcase/watercolor-2.mp4',  poster: '/showcase/watercolor-2.png' },
  { video: '/showcase/figurine-2.mp4',    poster: '/showcase/figurine-2.png' },
  { video: '/showcase/manga-2.mp4',       poster: '/showcase/manga-2.png' },
  { video: '/showcase/brick-2.mp4',       poster: '/showcase/brick-2.png' },
];

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

interface ShowcaseItemProps {
  video: string;
  poster: string;
}

/** Renders a video if available, falls back to the poster image on error. */
function ShowcaseItem({ video, poster }: ShowcaseItemProps) {
  const [videoFailed, setVideoFailed] = useState(false);

  if (videoFailed) {
    return (
      <img
        src={poster}
        alt=""
        className="w-full aspect-square object-cover"
        loading="eager"
      />
    );
  }

  return (
    <video
      src={video}
      poster={poster}
      autoPlay
      muted
      loop
      playsInline
      className="w-full aspect-square object-cover"
      onError={() => setVideoFailed(true)}
    />
  );
}

interface MarqueeColumnProps {
  items: ShowcaseItemProps[];
  speed: number;
  direction: 'up' | 'down';
}

function MarqueeColumn({ items, speed, direction }: MarqueeColumnProps) {
  const columnRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = columnRef.current;
    if (!el) return;

    let animationId: number;
    let position = direction === 'up' ? 0 : -el.scrollHeight / 2;

    const animate = () => {
      if (direction === 'up') {
        position -= speed;
        if (position <= -el.scrollHeight / 2) position = 0;
      } else {
        position += speed;
        if (position >= 0) position = -el.scrollHeight / 2;
      }
      el.style.transform = `translateY(${position}px)`;
      animationId = requestAnimationFrame(animate);
    };

    animationId = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(animationId);
  }, [speed, direction]);

  const doubled = [...items, ...items];

  return (
    <div className="overflow-hidden h-full relative">
      {/* Top fade */}
      <div
        className="absolute top-0 inset-x-0 h-20 z-10 pointer-events-none"
        style={{ background: 'linear-gradient(to bottom, #0A0A1A, transparent)' }}
      />
      {/* Bottom fade */}
      <div
        className="absolute bottom-0 inset-x-0 h-20 z-10 pointer-events-none"
        style={{ background: 'linear-gradient(to top, #0A0A1A, transparent)' }}
      />

      <div ref={columnRef} className="flex flex-col gap-4 will-change-transform">
        {doubled.map((item, i) => (
          <motion.div
            key={`${item.video}-${i}`}
            className="rounded-xl overflow-hidden shadow-lg"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: i * 0.04, duration: 0.4 }}
          >
            <ShowcaseItem video={item.video} poster={item.poster} />
          </motion.div>
        ))}
      </div>
    </div>
  );
}

export const ShowcaseGallery = memo(function ShowcaseGallery() {
  const [col1, setCol1] = useState(() => shuffleArray(SHOWCASE_ITEMS).slice(0, 6));
  const [col2, setCol2] = useState(() => shuffleArray(SHOWCASE_ITEMS).slice(0, 6));
  const [col3, setCol3] = useState(() => shuffleArray(SHOWCASE_ITEMS).slice(0, 6));
  const [rotating, setRotating] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => {
      setRotating(true);
      setTimeout(() => {
        setCol1(shuffleArray(SHOWCASE_ITEMS).slice(0, 6));
        setCol2(shuffleArray(SHOWCASE_ITEMS).slice(0, 6));
        setCol3(shuffleArray(SHOWCASE_ITEMS).slice(0, 6));
        setRotating(false);
      }, 400);
    }, 30_000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div
      className="h-full flex gap-4 px-4"
      style={{ opacity: rotating ? 0 : 1, transition: 'opacity 0.4s ease' }}
    >
      <div className="flex-1">
        <MarqueeColumn items={col1} speed={0.3} direction="up" />
      </div>
      <div className="flex-1">
        <MarqueeColumn items={col2} speed={0.25} direction="down" />
      </div>
      <div className="flex-1">
        <MarqueeColumn items={col3} speed={0.35} direction="up" />
      </div>
    </div>
  );
});
