"""Apple Wallet (.pkpass) generation for avatar cards."""

import hashlib
import io
import json
import logging
import os
import tempfile
import zipfile

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

from ..config import settings
from ..services import storage_service

logger = logging.getLogger(__name__)

router = APIRouter()


def _apple_wallet_configured() -> bool:
    return bool(
        settings.APPLE_PASS_TYPE_ID
        and settings.APPLE_PASS_TEAM_ID
        and settings.APPLE_PASS_CERT_PATH
        and settings.APPLE_PASS_KEY_PATH
        and settings.APPLE_WWDR_CERT_PATH
    )


def _download_avatar_bytes(video_id: str) -> bytes:
    """Download avatar PNG from GCS and return raw bytes."""
    from google.cloud import storage as gcs

    avatar_gcs_uri = f"gs://{settings.GCS_BUCKET}/avatars/{video_id}.png"
    client = gcs.Client(project=settings.GOOGLE_CLOUD_PROJECT)
    parts = avatar_gcs_uri.removeprefix("gs://").split("/", 1)
    bucket = client.bucket(parts[0])
    blob = bucket.blob(parts[1])
    return blob.download_as_bytes()


def _resize_image(img_bytes: bytes, size: tuple[int, int]) -> bytes:
    """Resize an image to the given (width, height) and return PNG bytes."""
    from PIL import Image

    img = Image.open(io.BytesIO(img_bytes)).convert("RGBA")
    img = img.resize(size, Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _build_pass_json(video_id: str) -> dict:
    """Build the pass.json content for a Generic pass."""
    share_page_url = f"{settings.PUBLIC_BASE_URL}/share/{video_id}"

    return {
        "formatVersion": 1,
        "passTypeIdentifier": settings.APPLE_PASS_TYPE_ID,
        "serialNumber": f"avatar-{video_id}",
        "teamIdentifier": settings.APPLE_PASS_TEAM_ID,
        "organizationName": "Gemini Motion Lab",
        "description": "Your AI Motion Avatar",
        "foregroundColor": "rgb(255, 255, 255)",
        "backgroundColor": "rgb(26, 35, 126)",
        "labelColor": "rgb(200, 220, 255)",
        "logoText": "Gemini Motion Lab",
        "barcode": {
            "message": share_page_url,
            "format": "PKBarcodeFormatQR",
            "messageEncoding": "iso-8859-1",
            "altText": "Scan to view video",
        },
        "barcodes": [
            {
                "message": share_page_url,
                "format": "PKBarcodeFormatQR",
                "messageEncoding": "iso-8859-1",
                "altText": "Scan to view video",
            }
        ],
        "generic": {
            "primaryFields": [
                {
                    "key": "title",
                    "label": "AI AVATAR",
                    "value": "Motion Avatar",
                }
            ],
            "secondaryFields": [
                {
                    "key": "event",
                    "label": "EXPERIENCE",
                    "value": "Gemini Motion Lab",
                }
            ],
            "auxiliaryFields": [
                {
                    "key": "type",
                    "label": "TYPE",
                    "value": "AI Generated",
                }
            ],
            "backFields": [
                {
                    "key": "info",
                    "label": "About",
                    "value": "This avatar was generated by Gemini AI at the Motion Lab experience. Visit the link to see your motion video!",
                },
                {
                    "key": "url",
                    "label": "Your Video",
                    "value": share_page_url,
                },
            ],
        },
    }


def _sign_manifest(manifest_json: bytes) -> bytes:
    """Sign the manifest.json using PKCS#7 detached signature."""
    from cryptography import x509
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.serialization import pkcs7

    # Load certificate
    with open(settings.APPLE_PASS_CERT_PATH, "rb") as f:
        cert = x509.load_pem_x509_certificate(f.read())

    # Load private key
    key_password = (
        settings.APPLE_PASS_KEY_PASSWORD.encode()
        if settings.APPLE_PASS_KEY_PASSWORD
        else None
    )
    with open(settings.APPLE_PASS_KEY_PATH, "rb") as f:
        private_key = serialization.load_pem_private_key(f.read(), password=key_password)

    # Load WWDR intermediate certificate
    with open(settings.APPLE_WWDR_CERT_PATH, "rb") as f:
        wwdr_cert = x509.load_pem_x509_certificate(f.read())

    # Create PKCS#7 detached signature (DER-encoded)
    signature = (
        pkcs7.PKCS7SignatureBuilder()
        .set_data(manifest_json)
        .add_signer(cert, private_key, hashes.SHA256())
        .add_certificate(wwdr_cert)
        .sign(serialization.Encoding.DER, [pkcs7.PKCS7Options.DetachedSignature, pkcs7.PKCS7Options.Binary])
    )

    return signature


def _build_pkpass(video_id: str, avatar_bytes: bytes) -> bytes:
    """Build a complete .pkpass ZIP archive."""

    # Prepare images — Apple Wallet expects specific sizes
    # icon.png: 29x29, icon@2x.png: 58x58, icon@3x.png: 87x87
    # thumbnail.png: 90x90, thumbnail@2x.png: 180x180
    # logo.png: 160x50 (we'll skip logo image, use logoText instead)
    files: dict[str, bytes] = {}

    files["icon.png"] = _resize_image(avatar_bytes, (29, 29))
    files["icon@2x.png"] = _resize_image(avatar_bytes, (58, 58))
    files["icon@3x.png"] = _resize_image(avatar_bytes, (87, 87))
    files["thumbnail.png"] = _resize_image(avatar_bytes, (90, 90))
    files["thumbnail@2x.png"] = _resize_image(avatar_bytes, (180, 180))

    # pass.json
    pass_json = _build_pass_json(video_id)
    files["pass.json"] = json.dumps(pass_json, indent=2).encode("utf-8")

    # manifest.json — SHA1 hash of every file
    manifest: dict[str, str] = {}
    for filename, data in files.items():
        manifest[filename] = hashlib.sha1(data).hexdigest()

    manifest_bytes = json.dumps(manifest, indent=2).encode("utf-8")
    files["manifest.json"] = manifest_bytes

    # signature — PKCS#7 detached signature of manifest.json
    files["signature"] = _sign_manifest(manifest_bytes)

    # Zip into .pkpass
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename, data in files.items():
            zf.writestr(filename, data)

    return buf.getvalue()


@router.get("/share/{video_id}/apple-wallet")
async def get_apple_wallet_pass(video_id: str):
    """Generate and return a .pkpass file for Apple Wallet."""
    if not _apple_wallet_configured():
        raise HTTPException(
            status_code=501,
            detail="Apple Wallet not configured. Set APPLE_PASS_TYPE_ID, APPLE_PASS_TEAM_ID, and certificate paths.",
        )

    # Check avatar exists
    avatar_gcs_uri = f"gs://{settings.GCS_BUCKET}/avatars/{video_id}.png"
    if not storage_service.gcs_blob_exists(avatar_gcs_uri):
        raise HTTPException(
            status_code=404,
            detail=f"Avatar not found for video_id={video_id}",
        )

    try:
        avatar_bytes = _download_avatar_bytes(video_id)
        pkpass_bytes = _build_pkpass(video_id, avatar_bytes)

        logger.info(f"Apple Wallet pass generated for video_id={video_id} ({len(pkpass_bytes)} bytes)")

        return Response(
            content=pkpass_bytes,
            media_type="application/vnd.apple.pkpass",
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to create Apple Wallet pass: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Apple Wallet error: {str(e)}")
